package com.sms.core.enums;

public enum FeatureKey {
    // Core — always on
    STUDENT_MANAGEMENT,
    ATTENDANCE,
    ACADEMIC_MANAGEMENT,
    NOTICE_BOARD,
    // Standard
    EXAM_MANAGEMENT,
    FEE_MANAGEMENT,
    ONLINE_FEE_PAYMENT,
    STAFF_HR,
    PAYROLL,
    PARENT_PORTAL,
    TIMETABLE,
    HOMEWORK,
    DOCUMENT_MANAGEMENT,
    REPORT_CARDS,
    // Advanced
    LIBRARY,
    TRANSPORT,
    GPS_TRACKING,
    HOSTEL,
    EXTRA_CURRICULAR,
    ACHIEVEMENTS,
    ONLINE_CLASSES,
    ASSIGNMENT_PORTAL,
    // Premium
    ANALYTICS_DASHBOARD,
    CUSTOM_REPORTS,
    BULK_SMS,
    WHATSAPP_INTEGRATION,
    FACE_RECOGNITION_ATTENDANCE,
    MULTI_BRANCH,
    API_ACCESS,
    WHITE_LABELLING,
    GRIEVANCE_PORTAL,
    ALUMNI_MODULE
}
